repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.6.0
    hooks:
      - id: cspell  # spellchecking
        pass_filenames: false
        args:
          - --config
          - cspell.json
          - README.md
          - docs/**/*.md